name = "CryptoDashApp"
uuid = "8f55a569-a1ee-45d2-b761-b2b316ddd8e9"
authors = ["Vikas Negi <vikas.negi10@gmail.com>"]
version = "0.1.5"

[deps]
AlphaVantage = "6348297c-a006-11e8-3a05-9bbf8830fd7b"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AlphaVantage = "0.3"
CSV = "0.8"
Dash = "0.1"
DashCoreComponents = "1.17"
DashHtmlComponents = "1.1, 2"
DataFrames = "1.2"
GLM = "1.5"
HTTP = "0.9"
JSON = "0.21"
PlotlyJS = "0.15"
Query = "1.0"
StatsBase = "0.33"
julia = "1.6"
