name = "CryptoDashApp"
uuid = "8f55a569-a1ee-45d2-b761-b2b316ddd8e9"
authors = ["Vikas Negi <vikas.negi10@gmail.com>"]
version = "0.6.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10"
Dash = "1.5"
DataFrames = "1.6"
GLM = "1.9"
HTTP = "1.10"
JSON = "0.21.4"
Mocking = "0.7"
PlotlyJS = "0.18"
StatsBase = "0.34"
julia = "1.8"
